### PR TITLE
Add needs triage label to new issues

### PR DESCRIPTION
**Pull request by fcollonval**
To add the triage label to all issues (even those not created from the template), I propose to add a event action on the bot.

cc @jweill-aws

### CODE REVIEW

**Comment by jtpio** [comment]
Do we need this now that https://github.com/jupyterlab/.github/pull/5 has been merged?

The new label seems to be showing up when creating a new issue:

image

**Comment by jtpio** [comment]
> even those not created from the template

Also opening a blank issue is disabled in: https://github.com/jupyterlab/.github/blob/4fce57b828b6ec400d1a07b971ca248f5b905d45/.github/ISSUE_TEMPLATE/config.yml#L1

**Comment by fcollonval** [comment]
@jasongrout pointed out at the dev meeting that an issue was not labelled with the triage label: https://github.com/jupyterlab/jupyterlab/issues/11792

I think this can happen if you add an issue using GitHub API (this is for example possible using the GitHub Issues and Pull Request plugin in VS Code). So this proposes a more robust way of ensuring the triage label is applied.

> This is probably the case of that issue as it also does not have the various sections from the template.

**Comment by JasonWeill** [comment]
Thanks! This looks good to me, although I don't have permission to merge it myself.

**Comment by jtpio** [comment]
Looks like new issues are being created without the new label, for example: https://github.com/jupyterlab/jupyterlab/issues/11811

image

Since the issue follows the template, I would have expected the label to have been added automatically, with the changes in https://github.com/jupyterlab/.github/pull/5?

**Comment by fcollonval** [comment]
> Looks like new issues are being created without the new label, for example: jupyterlab/jupyterlab#11811

That one is really weird indeed.

@blink1073 Does some actions need to be done manually when this is merged to update the bot on heroku?

**Comment by blink1073** [comment]
Yes, it is currently tied to my personal heroku account.  I'll push the update once this is merged.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
> Looks like new issues are being created without the new label, for example: jupyterlab/jupyterlab#11811

We should also investigate why the template approach didn't seem to work.

For Heroku, we could also create a `jupyterlab` team and add several people to it that would be able to push new versions?

**Comment by JasonWeill** [comment]
A few more issues opened today do not have the `status:Needs Triage` label:
* https://github.com/jupyterlab/jupyterlab/issues/11824 (I labeled it manually)
* https://github.com/jupyterlab/jupyterlab/issues/11825
* https://github.com/jupyterlab/jupyterlab/issues/11826

**Comment by blink1073** [comment]
> For Heroku, we could also create a jupyterlab team and add several people to it that would be able to push new versions?

Yeah, let's try that.  @jweill-aws, do you have an email associated with Heroku that I can add?  You can email me with the address.

**Comment by JasonWeill** [comment]
Sounds good! @blink1073 I just sent you the info.

**Comment by jtpio** [comment]
For reference the label was correctly added when creating this issue from the "New Issue" button on GitHub: https://github.com/jupyterlab/jupyterlab/issues/11843

**Comment by jtpio** [comment]
Looks like this change still needs to be deployed to Heroku.

@jweill-aws were you able to join the `jupyterlab` team on Heroku? Would you like to deploy the latest `master` there? Thanks!

**Comment by JasonWeill** [comment]
I added the upstream Heroku app (`mighty-mountain-44031`) as a remote called `heroku` and ran `git push heroku main`. Summary output:

```
remote: Verifying deploy... done.
To https://git.heroku.com/mighty-mountain-44031.git
   f5eb6fa..d3d09f4  main -> main
```

**Comment by blink1073** [comment]
> I added the upstream Heroku app (mighty-mountain-44031) as a remote called heroku and ran git push heroku main. Summary output:

Thanks @jweill-aws!

**Comment by jtpio** [comment]
Thanks!

Looks like the bot is up and running and now labeling issues.

However if labels other repos such as the ones under the `jupyter-server` org. Is that something we want?

For example: https://github.com/jupyter-server/jupyter_releaser/issues/247

image

**Comment by JasonWeill** [comment]
Seems like that's not necessary right now; our triage process is intended for use in JupyterLab only. Does the bot know which project it's running in?

**Comment by blink1073** [comment]
It could be made opt-in using a setting like the binder linker

**Comment by blink1073** [comment]
Or you could inspect the event and filter on the target repo org

**Pull request merged**
